name: geocoder
description: Forward and reverse geocoding.
version: 0.3.0
author: Aloïs Deniel<alois.deniel@gmail.com>
homepage: https://github.com/aloisdeniel/flutter_geocoder

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  meta: 1.3.0
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.aloisdeniel.geocoder
    pluginClass: GeocoderPlugin
